# /usr/src/linux-headers-$(uname -r)/include
#
# compile ub kernel
#
# 1. crosscompile eclipse
проблемы с путями

/home/zaqwes/emb-rpi/buildroot-2014.11/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabi-

что-то скомпилировал но на плате получил секфаулит